#!/usr/bin/env python3
"""Quantize the brand image's brain into a pixel bitmap -> core/src/brain.rs.

0 = empty, 1 = outline (dark stroke), 2 = pink fill.
"""
import sys
import os
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "/home/god/Pictures/screenshot-2026-04-08_23-04-31.png"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "core/src/brain.rs")
GRID_W = 46  # target pixel-art width

img = Image.open(SRC).convert("RGB")
W, H = img.size
px = img.load()


def classify(p):
    r, g, b = p
    if r > 190 and b > 170 and (r - g) > 35:
        return 2  # pink
    if max(r, g, b) < 110:
        return 1  # dark stroke
    return 0


# bounding box of pink (the brain is the only pink thing in the image)
xs, ys = [], []
for y in range(H):
    for x in range(W):
        if classify(px[x, y]) == 2:
            xs.append(x)
            ys.append(y)
if not xs:
    sys.exit("no pink pixels found")
m = 25  # margin to catch the black outline around the pink
x0, x1 = max(0, min(xs) - m), min(W - 1, max(xs) + m)
y0, y1 = max(0, min(ys) - m), min(H - 1, max(ys) + m)

bw, bh = x1 - x0 + 1, y1 - y0 + 1
grid_h = round(GRID_W * bh / bw)
cw, ch = bw / GRID_W, bh / grid_h

rows = []
for gy in range(grid_h):
    row = []
    for gx in range(GRID_W):
        dark = pink = total = 0
        for sy in range(int(gy * ch), int((gy + 1) * ch)):
            for sx in range(int(gx * cw), int((gx + 1) * cw)):
                c = classify(px[x0 + sx, y0 + sy])
                total += 1
                if c == 1:
                    dark += 1
                elif c == 2:
                    pink += 1
        if total and dark / total > 0.30:
            row.append(1)
        elif total and pink / total > 0.25:
            row.append(2)
        elif total and (dark + pink) / total > 0.45:
            row.append(1)
        else:
            row.append(0)
    rows.append(row)

# trim fully-empty border rows/cols
while rows and not any(rows[0]):
    rows.pop(0)
while rows and not any(rows[-1]):
    rows.pop()
while rows and not any(r[0] for r in rows):
    rows = [r[1:] for r in rows]
while rows and not any(r[-1] for r in rows):
    rows = [r[:-1] for r in rows]

gw, gh = len(rows[0]), len(rows)
with open(OUT, "w") as f:
    f.write("//! Pixelated brand brain, generated by tools/gen_brain.py from the\n")
    f.write("//! Arenda Innovations BrAIn OS artwork. 0 empty, 1 outline, 2 pink.\n\n")
    f.write(f"pub const BRAIN_W: usize = {gw};\n")
    f.write(f"pub const BRAIN_H: usize = {gh};\n\n")
    f.write(f"pub static BRAIN: [[u8; {gw}]; {gh}] = [\n")
    for r in rows:
        f.write("    [" + ", ".join(str(v) for v in r) + "],\n")
    f.write("];\n")

# terminal preview
for r in rows:
    print("".join(" .#"[0 if v == 0 else (2 if v == 2 else 1)].replace("#", "@").replace(".", "#") if False else (" " if v == 0 else ("#" if v == 1 else "o")) for v in r))
print(f"\nwrote {OUT}: {gw}x{gh}")
